# Generated by Django 5.1.15 on 2026-02-18 20:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_banner_cta_homepage_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.fields.RichTextField(blank=True, default='Banner Sub Title'),
        ),
    ]
