# Generated by Django 5.1.15 on 2026-02-20 18:39

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagecarouselimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='home.homepage'),
        ),
    ]
