# Generated by Django 5.1.15 on 2026-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepagecarouselimages_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimages',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
