# Generated by Django 5.1.15 on 2026-02-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email Address', max_length=100)),
                ('full_name', models.CharField(help_text='First Name and Last Name', max_length=100)),
            ],
        ),
    ]
